### ISSUE TITLE
Outdated delete_atoms command

### ISSUE THREAD

**Issue by simongravelle** [lammpstutorials/lammpstutorials.github.io#18]
Issue raised by Alireza Nazarahari: delete_atoms atom command in tutorial 2 must be updated to : 

delete_atoms random fraction 0.5 no all membrane 482793

**Comment by simongravelle** [comment]
fixed. also reduced system size and added warning for simulation duration

**Comment by ReadingRocks145** [comment]
I think I had the same issue: the command was 

delete_atoms random fraction 0.02 no rdel NULL 482793 bond yes

then I tried

delete_atoms random fraction 0.5 no all membrane 482793

I still get an error saying 

ERROR: Illegal delete_atoms command (src/delete_atoms.cpp:73)

Is there something I'm missing to fix this?
Thanks!

**Comment by simongravelle** [comment]
What is your LAMMPS version ?

**Comment by ReadingRocks145** [comment]
29 Sep 2021  - Update 2

**Comment by simongravelle** [comment]
That could be the issue, the delete_atoms command has evolved since then. Try with the last LAMMPS version, it should work.
